### ISSUE TITLE
Error on installing the plugin

### ISSUE THREAD

**Issue by worldofsmarty** [CptMeatball/pricetables#1]
I am facing the error on installing the plugin. I have successfully installed in localhost, But when i try the same in the server it gives the error as shown in screenshot. Kindly look into it and revert back asap.
Thank you for developing the plugin and its working perfectly fine in localhost.
I have done nothing wrong just installed the octobercms and pasted your plugin in the plugin directory and then by clicking on the cms gives this error. 

And when i click pricetables on the menubar it gives me this page is not found page. The URL says backend/cptmeatball/pricetables/prices

**Comment by CptMeatball** [comment]
Hi! I'm currently not working on this plugin. If I have the time I will check it out this evening or tomorrow, but I can't promise anything. 

As for the database error: Please try to log-out and log in again. This runs the database scripts that should build the tables.

I'll try and look into it. :)

**Comment by CptMeatball** [comment]
I've tested this on both my local and production environment and the plugin works just fine.

Something that pop to mind:

Be sure to add the source files of the plugin in the plugins directory under ````cptmeatball/pricetables````. If it is anything other than that you get a 404 in the back-end. This is because of the namespaces and hardcoded URLs that october uses for the plugins. 

Have you fixed your database error yet?

**Comment by worldofsmarty** [comment]
I can provide you the login details of the octobercms. If you would like to take a look at it. Can you Skype me on worldofsmarty so that we can interact.

**Comment by worldofsmarty** [comment]
Looks like the problem was with the capital letters used for the folders.
